photo_gallery/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from photo_gallery.models import Item, Photo
from photo_gallery.views import ItemList, ItemListView, ItemDetailView, PhotoDetailView

urlpatterns = [
    url(r'^$', 
        ItemList.as_view(template_name='index.html'),
        name='index',
    ),
    url(r'^items/$', ItemListView.as_view(),
        name='item_list'
    ),
    url(r'^items/(?P<pk>\d+)/$', ItemDetailView.as_view(),
        name='item_detail'
    ),
    url(r'^photos/(?P<pk>\d+)/$', PhotoDetailView.as_view(),
        name='photo_detail'
    ),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
]

photo_gallery_project/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from photo_gallery_project.settings import ROOT_URL

urlpatterns = [
    url(r'^%s' % ROOT_URL[1:], include('photo_gallery_project.real_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo_gallery/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import admin

from photo_gallery.fields import ThumbnailImageField

class Item(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    
    class Meta:
        ordering = ['name']
        
    def __unicode__(self):
        return self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('item_detail', None, {'pk': self.id})

class Photo(models.Model):
    item = models.ForeignKey(Item)
    title = models.CharField(max_length=100)
    image = ThumbnailImageField(upload_to='photos')
    caption = models.CharField(max_length=250, blank=True)
    
    class Meta:
        ordering = ['title']
        
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        return('photo_detail', None, {'pk': self.id})
        
class PhotoInline(admin.StackedInline):
    model = Photo
   
class ItemAdmin(admin.ModelAdmin):
    inlines = [PhotoInline]
    
admin.site.register(Item, ItemAdmin)
admin.site.register(Photo)

photo_gallery/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from photo_gallery.models import Item, Photo

class ItemList(TemplateView):

    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(ItemList, self).get_context_data(**kwargs)
        context['item_list'] = Item.objects.all()
        return context

class ItemListView(ListView):

    model = Item
    
class ItemDetailView(DetailView):

    model = Item
    
class PhotoDetailView(DetailView):

    model = Photo

photo_gallery/templates/base.html
<html>
    <head>
        <title>Gallery - {% block title %}{% endblock %}</title>
        <style type="text/css">
            body { margin: 30px; font-family: sans-serif; background: #fff; }
            h1 { background: #ccf; padding: 20px; }
            h2 { background: #ddf; padding: 10px 20px; }
            h3 { background: #eef; padding: 5px 20px; }
            table { width: 100% }
            table th { text-align: left; }
        </style>
    </head>
    <body>
        <h1>Gallery</h1>
        {% block content %}{% endblock %}
    </body>
</html>

photo_gallery/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}
{% block content %}

<h2>Welcome to the Gallery!</h2>
<p>Here you find pictures of various items. Below are some higthlighted items; use the link at the bottom to see the full listing.</p>

<h3>Showcase</h3>
<table>
    <tr>
        {% for item in item_list|slice:":3" %}
            <td>
                <a href="{{ item.get_absolute_url }}"><b>{{ item.name }}</b><br/>
                {% if item.photo_set.count %}
                    <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
                {% else %}
                    <span>No photos (yet)</span>
                {% endif %}
                </a>
            </td>
        {% endfor %}
    </tr>
</table>
<p><a href="{% url 'item_list' %}">View the full list &raquo;</a></p>
{% endblock %}

photo_gallery/templates/photo_gallery/item_detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content%}

<p><a href="{% url 'item_list' %}">&laquo; Back to full listing</a></p>

<h2>{{ object.name }}</h2>
<p>{{ object.description }}</p>

<h3>Photos</h3>
<table>
    <tr>
        <th>Title</th>
        <th>Thumbnail</th>
        <th>Caption</th>
    </tr>
    {% for photo in object.photo_set.all %}
    <tr>
        <td><i>{{ photo.title }}</i></td>
        <td>
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.image.thumb_url }}" />
            </a>
        </td>
        <td>{{ photo.caption }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

photo_gallery/templates/photo_gallery/item_list.html
{% extends 'base.html' %}

{% block title %}Item List{% endblock %}
{% block content %}

<p><a href="{% url 'index' %}">&laquo; Back to main page</a></p>

<h2>Items</h2>
{% if object_list %}
<table>
    <tr>
        <th>Name</th>
        <th>Sample Thumb</th>
        <th>Description</th>
    </tr>
    {% for item in object_list %}
    <tr>
        <td><i>{{ item.name }}</i></td>
        <td>
            {% if item.photo_set.count %}
            <a href="{{ item.get_absolute_url }}">
                <img src="{{ item.photo_set.all.0.image.thumb_url }}"/>
            </a>
            {% else %}
            (No photos currently upload)
            {% endif %}
        </td>
        <td>{{ item.description }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>There are currently no items to display.</p>
{% endif %}
{% endblock %}

photo_gallery/templates/photo_gallery/photo_detail.html
{% extends "base.html" %}

{% block title %}{{ object.item.name }} - {{ object.title }}{% endblock %}

{% block content %}

<a href="{{ object.item.get_absolute_url }}">&laquo; Back to {{ object.item.name }} detail page</a>

<h2>{{ object.item.name }} - {{ object.title }}</h2>
<img src="{{ object.image.thumb_url }}" />
{% if object.caption %}<p>{{ object.caption }}</p>{% endif %}

{% endblock %}